# Generated by Django 6.0.7 on 2026-07-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
            ],
        ),
    ]
